<?php

/**
 * @file
 * Functions for fakermaker
 */

use \Drupal\core\Entity\EntityTypeInterface;
use \Drupal\core\Field\BaseFieldDefinition;

/**
 * hook_form_FORM_ID_alter()
 */
function fakermaker_form_field_config_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'field_config_edit_form') {
  // copying from /core/modules/field_ui/src/Form/FieldConfigEditForm.php
    // in form context, can get default value here)
    $form['fakermaker_value'] =  array(
      '#type' => 'details',
      '#title' => t('Default generation value'),
      '#open' => TRUE,
      '#tree' => TRUE,
      '#description' => t('The default value for generating new content during generation. Generation. Generation.'),
    );

    $form['fakermaker_value']['generation'] = array(
      '#type' => 'textarea',
      '#title' => t('Generator text'),
      '#default_value' => 'lorem ipsum', // @todo, load from the existing settings value.
      '#rows' => 5,
      '#description' => t('here are some details about how this works'),
      '#weight' => -10,
    );
  }
   $tes = "testing";
}


/**
http://drupal.stackexchange.com/questions/176314/how-to-add-a-simple-checkbox-in-field-api
 */
// wut doez this do?!
//http://slides.com/dolaresko/d8-field-api
function fakermaker_entity_base_field_info(EntityTypeInterface $entity_type) {
  // @todo: Make this configurable and/or remove if
  //   https://drupal.org/node/476294 is resolved.
//  if ($entity_type->id() === 'node') {
//    $fields['fakermaker'] = BaseFieldDefinition::create('fakermaker')
//      ->setCustomStorage(TRUE)
//      ->setLabel(t('FAKER MAKER TESTING.'))
//      ->setTranslatable(TRUE)
//      ->setComputed(TRUE)
//      ->setDisplayOptions('form', array(
//        'type' => 'path',
//        'weight' => 30,
//      ))
//      ->setDisplayConfigurable('form', TRUE);
//
//    return $fields;
//  }
}


