# Schema for the configuration files of the FakerMaker module.

fakermaker.settings:
  type: config_object
  mapping:
    langcode:
      type: string
      label: 'Language code'
    settings:
      type: mapping
      label: 'Entity Type Settings'
      mapping:
        article:
          type: mapping
          label: 'Article'
          mapping:
            name:
              type: string
              label: 'Content Type Name'
            status:
              type: string
              label: 'Faker Status for Content Type'
            weight:
              type: integer
              label: 'Generation Order'
        page:
          type: mapping
          label: 'Page'
          mapping:
            name:
              type: string
              label: 'Content Type Name'
            status:
              type: string
              label: 'Faker Status for Content Type'
            weight:
              type: integer
              label: 'Generation Order'

fakermaker.type.page:
  type: config_object
  mapping:
    type:
      type: string
      label: 'Content Type'
    fields:
      type: mapping
      mapping:
        body:
          type: mapping
          label: 'Body Field'
          mapping:
            provider:
              type: mapping
              label: 'Faker Provider Information'
              mapping:
                type:
                  type: string
                  label: 'Faker Provider Type'
                lang:
                  type: string
                  label: 'Faker Provider Localization'
                settings:
                  type: mapping
                  label: 'Faker Field Settings'
                  mapping:
                    type:
                      type: string
                      label: 'Faker Function to use'
                    maxNbChars:
                      type: integer
                      label: 'Maximum number of characters to return'
                    indexSize:
                      type: integer
                      label: 'Number of words'

# for article content type
fakermaker.type.article:
  type: config_object
  mapping:
    type:
      type: string
      label: 'Content Type'
    fields:
      type: mapping
      mapping:
        body:
          type: mapping
          label: 'Body Field'
          mapping:
            provider:
              type: mapping
              label: 'Faker Provider Information'
              mapping:
                type:
                  type: string
                  label: 'Faker Provider Type'
                lang:
                  type: string
                  label: 'Faker Provider Localization'
                settings:
                  type: mapping
                  label: 'Faker Field Settings'
                  mapping:
                    type:
                      type: string
                      label: 'Faker Function to use'
                    maxNbChars:
                      type: integer
                      label: 'Maximum number of characters to return'
                    indexSize:
                      type: integer
                      label: 'Number of words'
        field_image:
          type: mapping
          label: 'Image Field'
          mapping:
            provider:
              type: mapping
              label: 'Faker Provider Information'
              mapping:
                type:
                  type: string
                  label: 'Faker Provider Type'
                lang:
                  type: string
                  label: 'Faker Provider Localization'
                settings:
                  type: mapping
                  label: 'Faker Field Settings'
                  mapping:
                    width:
                      type: integer
                      label: 'Width'
                    height:
                      type: integer
                      label: 'Height'
                    category:
                      type: string
                      label: 'Category'
                    randomize:
                      type: boolean
                      label: 'Randomize'
                    word:
                      type: string
                      label: 'Words'
                    gray:
                      type: boolean
                      label: 'Gray Scale'
        field_tags:
          type: mapping
          label: 'Taxonomy Reference Field'
          mapping:
            provider:
              type: mapping
              label: 'Faker Provider Information'
              mapping:
                type:
                  type: string
                  label: 'Faker Provider Type'
                lang:
                  type: string
                  label: 'Faker Provider Localization'
                settings:
                  type: mapping
                  label: 'Faker Field Settings'
                  mapping:
                    type:
                      type: string
                      label: 'Provider Function'
                    maxNbChars:
                      type: integer
                      label: 'Maximum Number of Characters'
                    indexSize:
                      type: integer
                      label: 'Index Size'
            dependencies:
              type: sequence
              label: 'Dependencies'
              sequence:
                type: string
                label: 'Module / Entity'
